[project]
name = "astro-boot"
version = "0.1.0"
description = "Asteroid game developed with pygame, as part of the Courses on Boot.dev."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pygame==2.6.1"]
